language: cpp

matrix:
  include:
    # - os: linux
    #   compiler: gcc
    #   sudo: required
    #   dist: trusty
    #   env: TARGET_DIST=trusty
    - os: linux
      compiler: gcc
      sudo: false
      dist: precise
      env: TARGET_DIST=precise

addons:
  apt:
    sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.4 main'
          key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
        - sourceline: 'deb-src http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.4 main'
          key_url: 'http://llvm.org/apt/llvm-snapshot.gpg.key'
        - kalakris-cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - build-essential
    - lcov
    - libcap-dev
    - flex
    - bison
    - cmake
    - libelf-dev
    - subversion
    - git
    - libtool
    - libpixman-1-dev
    - minisat
    - clang-3.4
    - llvm-3.4
    - llvm-3.4-dev
    - llvm-3.4-tools

before_install:
    ###########################################################################
    # Set up the locations to get various packages from
    # We assume the Travis image uses Ubuntu 12.04 LTS or 14.04 LTS
    ###########################################################################
    - if [[ "$TARGET_DIST" == "trusty" ]]; then
         sudo apt-get update;
         sudo apt-get remove libbison-dev bison ;
         sudo apt-get update;
         wget https://launchpad.net/ubuntu/+source/bison/1:2.5.dfsg-2.1/+build/3270698/+files/libbison-dev_2.5.dfsg-2.1_amd64.deb;
         wget https://launchpad.net/ubuntu/+source/bison/1:2.5.dfsg-2.1/+build/3270698/+files/bison_2.5.dfsg-2.1_amd64.deb;
         sudo dpkg -i libbison-dev_2.5.dfsg-2.1_amd64.deb;
         sudo dpkg -i bison_2.5.dfsg-2.1_amd64.deb;
         sudo apt-mark hold libbison-dev bison;
         export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/x86_64-linux-gnu/c++/4.8;
      fi

    ###########################################################################
    # Set up out of source build directory
    ###########################################################################
    - export CRETE_SRC=`pwd`
    - cd ../
    - mkdir build
    - cd build/
    - export BUILD_DIR=`pwd`

    ###########################################################################
    # Install stuff
    ###########################################################################
    # Install Clang as the compiler supporting C++11
    - if [[ "$TARGET_DIST" == "trusty" ]]; then
         wget http://llvm.org/releases/3.5.0/clang+llvm-3.5.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz;
         tar xf clang+llvm-3.5.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz;
         CXX=./clang+llvm-3.5.0-x86_64-linux-gnu/bin/clang cmake $CRETE_SRC;
      fi

    - if [[ "$TARGET_DIST" == "precise" ]]; then
         CXX=`which clang-3.4` cmake $CRETE_SRC;
      fi

script:
    # Build CRETE
    - make boost
    - make -j7